song_list = ['The Boy Is Mine', 'My Way', "You're Still The One", 'Adia', 'Make It Hot', 'Never Ever', 'Crush', 'Too Close', 'Come With Me', 'When The Lights Go Out', 'Cruel Summer', "Lookin' At Me", "Daydreamin'", 'The First Night', 'Friend Of Mine', 'Say It', 'Ghetto Supastar (That Is What You Are)', 'All My Life', 'Truly Madly Deeply', 'Nobody Does It Better', 'Ray Of Light', 'This Kiss', 'Gotta Be', 'Still Not A Player', 'To The Moon And Back', 'My All', 'I Still Love You', 'Sex And Candy', "Everybody [Backstreet's Back]", "Cleopatra's Theme", 'Looking Through Your Eyes', 'Stop', "They Don't Know", 'Intergalactic', 'Woof Woof', "Gettin' Jiggy Wit It", "I Don't Want To Wait", 'How Do I Live', "How's It Going To Be", 'Together Again', 'So Into You', 'Horse & Carriage', 'Ooh La La', 'I Get Lonely', 'Whatcha Gone Do?', 'I Got The Hook Up!', "I'm Alright", "Heaven's What I Feel", 'I Want You Back', 'Hey Now Now', "Shorty (You Keep Playin' With My Mind)", 'Goodbye To My Homies', "Money Ain't A Thang", 'Turn It Up [Remix]/Fire It Up', 'Destiny', 'Landslide', "There's Your Trouble", 'Ava Adore', 'Remember When', 'What U See Is What U Get', 'Black Ice (Sky High)', 'Touch It', 'The Arms Of The One Who Loves You', 'Paper', '26 Cents', "It's Alright", "What I Didn't Know", "Movin' On", 'If You Ever Have Forever In Mind', 'You Only Have To Say You Love Me', 'Ninety Nine [Flash The Message]', "How Do I Say I'm Sorry", "You Won't Forget Me", "Can't We Try", 'Stepping Stone', 'Cheated (To All The Girls)', "The Cup Of Life (The Official Song Of The World Cup, France '98)", 'Delicious', 'Here We Go Again', 'Spark', 'Freak Out', 'Ding-A-Ling', '2 Way Street', 'Recover Your Soul', 'One Heart At A Time', 'There You Are', 'Do Your Thing', 'Wishlist', 'Stop Being Greedy', 'I Can Do That', 'Push It', 'Love For Free', 'The Rockafeller Skank', 'Love The Way', 'Cover You In Kisses', 'Now That I Found You', 'Not About Romance', 'I Just Want To Dance With You', 'I Honestly Love You (David Foster Vers.)', 'Money, Power & Respect']


current_user = {'display_name': 'Benton Crook', 'external_urls': {'spotify': 'https://open.spotify.com/user/bentoncrook98'}, 'followers': {'href': None, 'total': 1}, 'href': 'https://api.spotify.com/v1/users/bentoncrook98', 'id': 'bentoncrook98', 'images': [{'height': 300, 'url': 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=1082651685483151&height=300&width=300&ext=1732360376&hash=Aba6UA9CaRii5PuGYH_hjIga', 'width': 300}, {'height': 64, 'url': 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=1082651685483151&height=50&width=50&ext=1732360376&hash=AbbFOjZU40Prh327vBB939Zr', 'width': 64}], 'type': 'user', 'uri': 'spotify:user:bentoncrook98'}


travel_to_date = "1998-08-13"
year = travel_to_date.split("-")[0]
print(year)


json = ""